bs: add file passthrough argument

diff --git a/bs b/bs
--- a/bs
+++ b/bs
@@ -27,23 +27,39 @@ function _check_is_dir
     end
 end
 
-argparse -s                                         \
-    e/env-pass=+'!_check_is_env "$_flag_value"'     \
-    w/workdir='!_check_is_dir "$_flag_value"'       \
-    c/clear-env                                     \
-    h/help                                          \
-    -- $argv                                        \
+function _check_file_exists
+    for v in $argv
+        set p (path resolve $v)
+        if ! test -e "$p"
+            echo "path does not exist: $v" >&2
+            exit 1
+        end
+    end
+end
+
+argparse -s                                               \
+    e/env-pass=+'!_check_is_env "$_flag_value"'           \
+    f/ro-file-pass=+'!_check_file_exists "$_flag_value"'  \
+    w/workdir='!_check_is_dir "$_flag_value"'             \
+    c/clear-env                                           \
+    h/help                                                \
+    -- $argv                                              \
 
 # Print help
 if set -q _flag_help
     echo "Usage:"
-    echo "  -e, --env-pass   passthrough an environment variable"
-    echo "  -w, --workdir    set the working directory"
+    echo "  -e, --env-pass       passthrough an environment variable"
+    echo "  -f, --ro-file-pass   passthrough files and directories to the sandbox (readonly)"
+    echo "  -w, --workdir        change working directory before executing"
     echo "  -c, --clear-env"
     echo "  -h, --help"
     exit
 end
 
+
+#
+# Make bubblewrap arguments
+#
 begin
     # Bubblewrap
     set -a bwrap_args \
@@ -62,9 +78,6 @@ begin
         --dir /run/user/"$(id -u)"                  \
         --dir /tmp                                  \
         --dir /var                                  \
-        --file 11 /etc/passwd                       \
-        --file 12 /etc/group                        \
-        --file 13 /etc/resolv.conf                  \
         --hostname computer                         \
         --proc /proc                                \
         --ro-bind /usr /usr                         \
@@ -74,7 +87,38 @@ begin
         --symlink usr/lib64 /lib64                  \
         --symlink usr/sbin /sbin                    \
 
-    # Namespace
+    #
+    # Make temporary files
+    #
+    set tmpdir (mktemp -d)
+
+    # /etc/group
+    set group_fd $tmpdir/group
+    getent group  65534 | sed 's/nobody/user/; s/65534/'"$(id -g)/" > $group_fd
+    set -a bwrap_args --ro-bind $group_fd /etc/group
+
+    # /etc/passwd (all users)
+    set passwd_fd $tmpdir/passwd
+    getent passwd 65534 | sed 's/nobody/user/; s/65534/'"$(id -u)/" > $passwd_fd
+    set -a bwrap_args --ro-bind $passwd_fd /etc/passwd
+
+    # /etc/resolv.conf (dns)
+    set resolv_fd $tmpdir/resolv.conf
+    echo "nameserver 1.1.1.1" >$resolv_fd
+    set -a bwrap_args --ro-bind $resolv_fd /etc/resolv.conf
+
+    # Hosts file (localhost)
+    set hosts_fd $tmpdir/hosts
+    string join -- '' '# Standard host addresses'\n          \
+         '127.0.0.1  localhost'\n                            \
+         '::1        localhost ip6-localhost ip6-loopback'\n \
+         'ff02::1    ip6-allnodes'\n                         \
+         'ff02::2    ip6-allrouters'\n                       \
+         '# This host address'\n                             \
+         "127.0.1.1  computer" >$hosts_fd
+    set -a bwrap_args --ro-bind $hosts_fd /etc/hosts
+
+    ## Namespace
     set -a bwrap_args    \
         --unshare-all    \
         --unshare-user   \
@@ -85,29 +129,35 @@ begin
         --unshare-cgroup \
         --disable-userns \
 
-    # Display
+    ## Display
     set -a bwrap_args \
         --ro-bind /run/user/"$(id -u)"/"$WAYLAND_DISPLAY" /run/user/"$(id -u)"/"$WAYLAND_DISPLAY" \
         --ro-bind-try /run/user/"$(id -u)"/pipewire-0 /run/user/"$(id -u)"/pipewire-0 \
         --ro-bind-try /run/user/"$(id -u)"/pulse /run/user/"$(id -u)"/pulse
 
-    # Process working directory
+    ## Process working directory
     if set -q _flag_workdir
         set path (path resolve $_flag_workdir)
         set workdir (path basename $path)
-        set -a bwrap_args --bind "$(path resolve $_flag_workdir)" /"$workdir"
+        set -a bwrap_args --bind "$(path resolve $_flag_workdir)" /project/"$workdir"
     else
         set workdir (basename "$PWD")
-        set -a bwrap_args --bind "$PWD" /"$workdir"
+        set -a bwrap_args --bind "$PWD" /project/"$workdir"
     end
 
-
-    # TODO: make a flag for this
-    if ! set -q __flag_
-        set -a bwrap_args                               \
-            --ro-bind ~/.bashrc /home/user/.bashrc      \
-            --ro-bind /etc/bash.bashrc /etc/bash.bashrc \
-            --ro-bind /etc/resolv.conf /etc/resolv.conf
+    # Passthrough
+    if set -q _flag_ro_file_pass
+        set -l home "$(string escape --style=regex -- "$HOME")"
+        for f in $_flag_ro_file_pass
+            if string match -rq -- ':' $f
+                set f (string split --max 1 -- : $f)
+                set f_inside (string replace "^$home" '/home/user' -- $f[2])
+                set -a -- bwrap_args --ro-bind "$f" "$f_inside"
+            else if test (count $f) = 1
+                set f_inside (string replace -r -- "^$home" '/home/user' $f)
+                set -a -- bwrap_args --ro-bind "$f" "$f_inside"
+            end
+        end
     end
 
     # Networking
@@ -136,26 +186,16 @@ begin
 
     # Setup current working directory
     set -a bwrap_args             \
-        --chdir /"$workdir"       \
-        --dir /"$workdir"         \
+        --chdir /project/"$workdir"   \
+        --dir /project/"$workdir"     \
 
 end
 
-set tmpdir (mktemp -d)
-
-set group_fd $tmpdir/group
-getent group  65534 | sed 's/nobody/user/; s/65534/'"$(id -g)/" > $group_fd
-
-set passwd_fd $tmpdir/passwd
-getent passwd 65534 | sed 's/nobody/user/; s/65534/'"$(id -u)/" > $passwd_fd
-
-set resolv_fd $tmpdir/resolv
-echo "nameserver 1.1.1.1" >$resolv_fd
-
+#
+# Run bubblewrap
+#
 bwrap $bwrap_args                     \
-      /bin/sh -c 'exec "$@"' -- $argv \
-    11<$passwd_fd                     \
-    12<$group_fd                      \
-    13<$resolv_fd                     \
+      /bin/sh -c 'exec "$@"' -- $argv
 
-rm $group_fd $passwd_fd $resolv_fd
+# cleanup
+rm -r "$tmpdir"
